image: golang:1.16

stages:
  - test
  - deploy

test:
  stage: test
  image: docker:19.03.12
  script:
    - docker build -f Dockerfile.test -t judger_test .
    - sh test.sh

deployJob:
  image: docker:19.03.12
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
