image: golang:1.16

stages:
  - test
  - deploy

test:
  stage: test
  image: docker:19.03.12
  script:
    - docker build -f Dockerfile.test -t judger_test .
    - docker run -v $PWD:/code -v $PWD/testcase/case/:/test_case \
               --tmpfs /judger/run:exec \
               --tmpfs /judger/spj:exec \
               --tmpfs /log \
               --tmpfs /tmp \
               --rm  --read-only\
               --cap-drop FSETID \
               --cap-drop MKNOD \
               --cap-drop SETFCAP \
               --cap-drop SETPCAP \
               --cap-drop NET_BIND_SERVICE \
               --cap-drop SYS_CHROOT \
               judger_test /bin/bash -c "python3 test.py"

deployJob:
  image: docker:19.03.12
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
