image:
  file: Dockerfile
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - vincaslt.highlight-matching-tag
    - ms-python.python
    - SonarSource.sonarlint-vscode
    - TabNine.tabnine-vscode
    
