stages:
  - test
  - deploy

test:
  stage: test
  image: docker:19.03.12
  script:
    - docker build -f test.gitlab.Dockerfile -t gitlab_judger_test .
    - sh test.gitlab.sh
    - docker rmi gitlab_judger_test

deployJob:
  image: docker:19.03.12
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - docker pull ubuntu:18.04
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker logout
    - docker rmi $IMAGE_TAG
